name: Pipeline para Build, Test e Deploy de Aplicação Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SAST Analysis via Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: python.lang.security.yaml

      - name: Envio de Alertas via Telegram
        if: always()
        uses: appleboy/telegram-action@master 
        with:
          to: ${{secrets.TELEGRAM_CHAT_ID}}
          token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          message: "Pipeline de build e test concluída. Resultados da varredura de vulnerabilidades:"
          format: markdown
          file: semgrep/results.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Ngrok
        uses: w3cj/action-ngrok@master
        with:
          auth_token: ${{secrets.NGROK_AUTH_TOKEN}}
          region: us

      - name: Deploy da Aplicação
        run: |
          npm install
          npm run build
          npm start
