name: Exemplo de Fluxo de Trabalho com Três Estágios
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker image build
        uses: docker/build-push-action@v4.0.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Configurar Ambiente
        run: echo "Configurando o ambiente"
      - name: Compilar
        run: echo "Compilando o código"
      - name: Testar
        run: echo "Executando os testes"
