name: Exemplo de Fluxo de Trabalho para Acessar um Contêiner Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username : ${{secrets.DOCKERHUB_USER}}
          password : ${{secrets.DOCKERHUB_PWD}}

      - name: Build do contêiner
        run: docker build -t imagem-nova:latest .

      - name: Run do contêiner
        run: docker run -d -p 8080:80 imagem-nova:latest
