name: Pipeline para Build, Test e Deploy de Aplicação Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run SAST Analysis via Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: python.lang.security.yaml

      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      
      - name: Deploy da Aplicação
        run: |
          npm install
          npm run build
          npm start
