name: Exemplo de Fluxo de Trabalho com Três Estágios
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configurar Ambiente
      run: echo "Configurando o ambiente"
    - name: Compilar
      run: echo "Compilando o código"
    - name: Testar
      run: echo "Executando os testes"
