name: Exemplo de Fluxo de Trabalho para Acessar um Contêiner Docker



      - name: Login no Docker Hub
        uses: docker/login-action@v1
        with:
          username : ${{secrets.DOCKERHUB_USER}}
          password : ${{secrets.DOCKERHUB_PWD}}


      - name: Run do contêiner
        run: docker run -d -p 8080:80 imagem-nova:latest
